name: CI-CD with ArgoCD

on:
  push:
    branches:
      - main
      - anoosha

jobs:
  ci:
    name: Build Docker Images and Push to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Shorten commit ID
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build backend with Maven
        working-directory: ./backend
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projectory-backend:${{ env.COMMIT_ID }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projectory-frontend:${{ env.COMMIT_ID }}

    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    name: Update Manifests and Sync ArgoCD
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Checkout Manifests Repo
        uses: actions/checkout@v2
        with:
          repository: AnooshaaAli/DevOps-Project-Projectory-K8s
          token: ${{ secrets.MANIFESTS_REPO_PAT }}
          path: manifests

      - name: Update Image Tags in Kubernetes YAMLs
        working-directory: manifests
        run: |
          sed -i '' "s|image: .*/projectory-backend:.*|image: ***\/projectory-backend:f1446d|" Kubernetes/Backend/backend-deployment.yaml
          sed -i '' "s|image: .*/projectory-frontend:.*|image: ***\/projectory-frontend:f1446d|" Kubernetes/Frontend/frontend-deployment.yaml

- name: Commit and push changes
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "github-actions@github.com"
    git add .
    git diff-index --quiet HEAD || git commit -m "Update image tags to ${{ env.COMMIT_ID }}"
    git push

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-darwin-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd

      - name: Sync ArgoCD App
        run: |
          argocd login my-argocd-server.argocd \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure \
            --grpc-web
          argocd app sync projectory-app